name: Dependency Check Workflow

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Check for circular dependencies
        run: npx madge --circular --extensions ts .
      
      - name: Check for duplicate dependencies
        run: npx depcheck
      
      - name: Check for known vulnerabilities
        run: npm audit
        
      - name: Check dependency updates
        run: |
          npx npm-check-updates > updates.txt
          echo "Available updates:" >> $GITHUB_STEP_SUMMARY
          cat updates.txt >> $GITHUB_STEP_SUMMARY
      
      - name: Verify peer dependencies
        run: npx check-peer-dependencies
      
      - name: Build verification
        run: npm run build
      
      - name: Run tests
        run: npm test -- --watch=false --browsers=ChromeHeadless